version: '2'
services:
  base:
    image: node:10
    volumes:
      - .:/usr/src/:delegated
    working_dir: /usr/src/
    environment:
      - NODE_ENV=development
#   install:
#     extends:
#       service: base
#     command: npm install
  build-dmd-client:
    extends:
      service: base
    command: npm run build:dmd-client -- --watch
  build-dmd-server:
    extends:
      service: base
    command: npm run build:dmd-server -- --watch
  start-dmd-api:
    extends:
      service: base
    ports:
      - 3000:3000
    command: npm run start:dmd-api
